name: login_flutter
description: A flutter login model app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  introduction_screen: ^3.1.12
  card_swiper: ^3.0.1

dev_dependencies:flutter:
  uses-material-design: true
  flutter_native_splash: ^2.3.4

  assets:
         
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#42a5f5"



flutter:
  uses-material-design: true

  assets:
    - assets/Logo.png
    - assets/category1.png
    - assets/category2.png
    - assets/category3.png
    - assets/category4.png
    - assets/Gallery/gallery1.jpg
    - assets/Gallery/gallery2.jpg
    - assets/Gallery/gallery3.jpg
    
